version: "3"
services:
  tcp-server:
    restart: always
    build: ./
    command: python3 -u ./server.py
    ports:
      - "8181:8181"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"